search_space:
  attention_hidden_size: [256]
  feedforward_hidden_size: [512]
  num_decoder_layers: [4]
  num_attention_heads: [8]
  epochs: [150]
  seed: [0]
  learning_rate: [0.0001, 0.0003, 0.0006]
  batch_size: [4, 8]
  accumulation_steps: [1]
  embed_dropout: [0.1]
  ffn_dropout: [0.1, 0.2]
  attn_dropout: [0.1, 0.2]
  attn_proj_dropout: [0.1]
  weight_decay: [0.01]
